### ISSUE TITLE
Flies should be be able to fly

### ISSUE THREAD

**Issue by g33kex** [PainsPerdus/gboi-rocket#103]
Currently, flies can collide with rocks. That's bad, because flies can fly above rocks. They're stupid. Please make them less stupid. 

Quick and dirty fix, hack as we like them: Just add another speed variable for the flies to not go through the collision checks and move them manually, that works.

**Comment by JeanMarieMineau** [comment]
Currently, the are able to fly. But that way too dirty. It will be unfix soon...

**Comment by g33kex** [comment]
I love the way it is. Very cool.

**Comment by DorianBourgeoisat** [comment]
Now they are
