### ISSUE TITLE
Regression : Isaac now cannot pass between rocks

### ISSUE THREAD

**Issue by DorianBourgeoisat** [PainsPerdus/gboi-rocket#125]
Isaac used to be able to go through 2 rocks separated by a 1 square space. Now he cannot. The hitbox is too large on the x axis.
Maybe related to #124

**Comment by DorianBourgeoisat** [comment]
only on branch display, and the problem has disapeared. I'm closing the issue

**Comment by Pascakk** [comment]
This issue is basically the same as #124
