### ISSUE TITLE
It's 5.30 AM

### ISSUE THREAD

**Issue by histausse** [PainsPerdus/gboi-rocket#133]
It's 5.30 am, we are all sleep drunk, and we are still coding assembly and reviewing stuff and managing the GitHub. May the FMS have mercy upon our souls.

**Comment by Thomyrock** [comment]
(╯°□°）╯︵ ┻━┻

**Comment by histausse** [comment]
┬─┬ ノ( ゜-゜ノ)

**Comment by Thomyrock** [comment]
(╯°□°）╯︵ ┻━┻

**Comment by histausse** [comment]
┬─┬ ノ( ゜-゜ノ)

**Comment by Thomyrock** [comment]
(╯°□°）╯︵ ┻━┻

**Comment by histausse** [comment]
![Alt Text](https://media.giphy.com/media/3o6gDQWOxr29QwXEac/giphy.gif)

**Comment by g33kex** [comment]
qergsgjdykul:lfyuydtgsdtjkfuykiydgtqes

**Comment by yberreby** [comment]
Y'all really need to get some sleep :')

**Comment by histausse** [comment]
Sleep is overrated. At least that what the third voice in my head tells me.

**Comment by yberreby** [comment]
Fixed by [#42](https://en.wikipedia.org/wiki/Coffee).
