### ISSUE TITLE
Controls UP/DOWN are swapped with RIGHT/LEFT

### ISSUE THREAD

**Issue by g33kex** [PainsPerdus/gboi-rocket#31]
UP and DOWN buttons update isaac's x position and LEFT and RIGHT update isaac's y position.  

It should be the opposite, UP and DOWN for y and LEFT and RIGHT for x. 

The bug is in the movement handling system: https://github.com/PainsPerdus/gboi-rocket/blob/5800e153d7a668960b1b72df0f7148ea81aafade/src/movement.s.stub

**Comment by JeanMarieMineau** [comment]
Working on it
