### ISSUE TITLE
Binary includes are in src folder instead of include folder

### ISSUE THREAD

**Issue by g33kex** [PainsPerdus/gboi-rocket#4]
Binary files (`.bin`) are mixed with source files (`.s`). I think this is bad practice

https://github.com/PainsPerdus/gboi-rocket/blob/8475000a2b568d3f595f7577a5bc9f07bf3e5df8/Makefile#L14

I don't know if wla-gb supports it but we'd need a separate folder for  
`.INCLUDE` that includes a source file (stored in `src/`)
and
`.INCBIN` that includes in a binary file (stored in `include/`)

**Comment by JeanMarieMineau** [comment]
There are now in ./src/sprites.
