### ISSUE TITLE
Isaac speed isn't null when blocked against a rock

### ISSUE THREAD

**Issue by g33kex** [PainsPerdus/gboi-rocket#49]
When Isaac is trying to walk into a rock, it's speed is not 0, so the walk animation continues to play.

**Comment by JeanMarieMineau** [comment]
Not a bug, (yet).
I'll look into it. If it doesn't raise any issues I'll edit the speed on collision.

**Comment by JeanMarieMineau** [comment]
I'm working on it, it should be solved shortly.

**Comment by JeanMarieMineau** [comment]
fix in #57
