### ISSUE TITLE
Isaac should not move while pressing two opposed directionnal keys

### ISSUE THREAD

**Issue by Pascakk** [PainsPerdus/gboi-rocket#54]
Isaac's speed should be equal to zero while pressing ← and → or ↑ and ↓  simultaneously.

**Comment by JeanMarieMineau** [comment]
Hum, I'll look into it, for now pressing two opposite directions is undefined behavior (although you can look into the pseudo code to find how it works).
I'll try to fix this in my next patch.

**Comment by g33kex** [comment]
Pressing two opposite directions isn't possible on the console itself.

**Comment by JeanMarieMineau** [comment]
If it's not a pb with the console, I won't touch it. If you want to fix this feel free though.

**Comment by Pascakk** [comment]
For some reason, it seems to depend on the emulator used to run the game. It won't be an issue in a physical gameboy anyway because of the design of directional pad.
