### ISSUE TITLE
Isaac still moves too fast.

### ISSUE THREAD

**Issue by Pascakk** [PainsPerdus/gboi-rocket#65]

**Comment by g33kex** [comment]
We need to have a sort of counter in the game loop to control when the speed is added to isaac's x position and also when the next animation frame is loaded. For now, there is just a manual timer for isaac's walk animation, but it would be better to have a global one. That's what I recommended in #62 

Another approach would be to use the timer interrupt to get (somewhat) fixed triggers, but I don't know which solution is best.

**Comment by JeanMarieMineau** [comment]
Not close yet.

**Comment by g33kex** [comment]
I think #111 fixes that.
