### ISSUE TITLE
Move the stack to the wram

### ISSUE THREAD

**Issue by JeanMarieMineau** [PainsPerdus/gboi-rocket#78]
Advice from the gbdev discord server:
ISSOtm:
The stack goes at $D000 if using WRAM banks, $E000 otherwise
Dorian what do you think?

**Comment by DorianXGH** [comment]
Good idea
Should be as simple as
~~~asm
ld SP, $E000
~~~

**Comment by DorianXGH** [comment]
#106 solved this issue
