### ISSUE TITLE
Isaac is slower when moving in the x axis than the y axis.

### ISSUE THREAD

**Issue by g33kex** [PainsPerdus/gboi-rocket#80]
When isaac moves left and right, it's a bit slower than when he moves up and down.
He takes about 1.73 seconds to go from the top to the bottom of the screen, and 1.93 seconds to go from the left to the right of the screen. 

Emulator used : sameboy.

**Comment by g33kex** [comment]
It's probably just an impression... If somebody can test this to see if they got the same impression or not.

**Comment by DorianXGH** [comment]
It seems to just be an impression, I don't see it. The difference you measured is likely to simply be the fact that the screen is rectangular and not a square

**Comment by g33kex** [comment]
That must be it, thank you Dorian!
