### ISSUE TITLE
Update tear struct for recycling

### ISSUE THREAD

**Issue by JeanMarieMineau** [PainsPerdus/gboi-rocket#94]
Values needed for recycling tears:
x
y
recycle flag, if the tear needs to be recycled.
inchain flag: if the tear is in a recycling chain.
init flag: if the tear is the first in a recycling chain.
OAM_ID: 4 or 5 bits (id of the sprite in OAM)

If possible, the tears should be in an array with access to the element with a 1byte address.
the `alive` information is stored with `y` (y = 0: the tear is not used)

**Comment by g33kex** [comment]
I approve that.

**Comment by g33kex** [comment]
#101 fixes it, be we still need to update the documentation.
